# Generated by Django 4.2 on 2024-05-09 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlelike',
            old_name='user_id',
            new_name='user',
        ),
    ]
