# Generated by Django 4.2 on 2024-05-07 03:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0003_remove_article_like_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='like_count',
            field=models.ManyToManyField(null=True, related_name='like_articles', to=settings.AUTH_USER_MODEL),
        ),
    ]
