# Generated by Django 4.2 on 2024-05-09 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_rename_user_id_articlelike_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlelike',
            old_name='like_count',
            new_name='like',
        ),
    ]
